### ISSUE TITLE
NR1: Security requirements

### ISSUE THREAD

**Issue by altaimeh** [WSU-4110/warrior-gains#16]
|NR1.  Security requirements|
|---|
|**Goal**: Validate user-id and passwords
**Stakeholders:** Users|
| **Description:** Users' login information should be protected. Unauthorize users will not have the ability to change them. Also, authorized users will not be denied from accessing their accounts. |
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |  
|**Date:** 09/30/2021  
|  **Priority:** 1 |

**Comment by omar-faruk01** [comment]
Implemented PassportJS to hash and salt password, ensured all emails have wayne.edu, enabled cookies and sessions for users, and password confirmation functionality.
